services:
  microservices-demo-birthdays-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: birthdaydb
    volumes:
      - mongo-data:/data/db

  microservices-demo-birthday-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - microservices-demo-birthdays-mongo
    environment:
      MONGO_URL: mongodb://microservices-demo-birthdays-mongo:27017/birthdaydb

volumes:
  mongo-data:
    driver: local
