services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: birthdaydb
    volumes:
      - mongo-data:/data/db

  birthday-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGO_URL: mongodb://db:27017/birthdaydb

volumes:
  mongo-data:
