version: '3.8'
services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017

volumes:
  db_data:
